apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-disk
  namespace: anticorona
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi